/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [muestra_id]
      ,[gmuestra_id]
      ,[pmuestra_id]
      ,[fecha_muestreo]
      ,[fecha_recepción]
      ,[fecha_reporte]
      ,[parametro_id]
      ,[caudal]
      ,[lluvia]
      ,[tipo_agua]
      ,[tipo_muestreo]
      ,[valor]
  FROM [dbo].[F_Muestra]